{% set name = "nds2-client-swig" %}
{% set version = "0.16.5" %}
{% set sha256 = "861c246a6959bdd9a704550a6fac749a1b7f0fe3f7a5d5e372bddcc36f6797fc" %}
{% set nds2_client_version = "0.16.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - macos-static-python.patch  # [osx]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - make  # [not win]
    - pkg-config  # [not win]
  host:
    - swig >=3.0.7
    - nds2-client >={{ nds2_client_version }}
test:
  commands:
    - test -f ${PREFIX}/include/nds2-client/nds.i  # [unix]
    - test -f ${PREFIX}/include/nds2-client/nds_swig.hh  # [unix]

outputs:
  - name: nds2-client-swig

  - name: python-nds2-client
    script: install-python.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake >=3.6
        - pkg-config  # [not win]
        - make  # [not win]
      host:
        - nds2-client >={{ nds2_client_version }}
        - {{ pin_subpackage('nds2-client-swig', exact=True) }}
        - numpy
        - python
        - swig >=3.0.7
      run:
        - nds2-client >={{ nds2_client_version }}
        - python
        - {{ pin_compatible('numpy') }}
    test:
      imports:
        - nds2
    about:
      home: https://wiki.ligo.org/Computing/NDSClient
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: Python extensions for NDS2
      description: |
        This provides python wrappers for the nds2 client.

about:
  home: https://wiki.ligo.org/Computing/NDSClient
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: NDS2 Client interface SWIG wrappings
  description: This provides SWIG interface files for the NDS2 client.

extra:
  recipe-maintainers:
    - duncanmmacleod
